### ISSUE TITLE
add service count to "idl list"

### ISSUE THREAD

**Issue by breerly** [uber/idl#14]
for example:

```
$ idl list

Listing 20 services

- ...
- ...
- ...
```

**Comment by breerly** [comment]
Would much rather have a `-json` flag that can be used with `jq` for programmability. `idl list` is for humans first.

**Comment by junchaowu** [comment]
nice

On Thu, Oct 22, 2015 at 1:38 PM, malandrew <notifications@github.com> wrote:

> Closed #14 <https://github.com/uber/idl/issues/14>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uber/idl/issues/14#event-443108028>.
>



-- 
Junchao Wu
Software Engineer @ Uber
