### ISSUE TITLE
idl update does not remove old service files

### ISSUE THREAD

**Issue by prashantv** [uber/idl#23]
If a service renames a service thrift file, both the old file and the new file are kept around in the idl repository. idl should not just append, but sync the folder to match the folder in the original repository.

**Comment by malandrew** [comment]
This should not be the case. The code definitely blows stuff away when updating a publisDid the service name change at all as well? Can you give me a way to reproduce this so I know exactly what the problem is.

**Comment by prashantv** [comment]
I'll send you the repo information offline.

**Comment by malandrew** [comment]
Can you install 3.1.3 and update the thrift files in your project and see if the publish resolves it?

**Comment by prashantv** [comment]
I installed 3.1.3, and ran `idl publish` from the root of curly - nothing happened.
