### ISSUE TITLE
Unparsable meta.json does not throw an error

### ISSUE THREAD

**Issue by dnathe4th** [uber/idl#32]
Without realizing it, I ended up with a merge conflict in my `meta.json` file after pulling from a remote. It looked something like this as you might imagine:

```
{
<<<<<<< remote commit
    "time": "2016-01-28T05:57:18.879Z",
    "version": 1453960638879,
    "remotes": {
        "repo-1": {
            "time": 1453960638879,
            "version": 1453960638879,
            "shasums": {
                "repo-1.thrift": "repo-1.hash"
=======
    "time": "2016-02-09T02:22:18.987Z",
    "version": 1454984538987,
    "remotes": {
        "repo-2": {
            "time": 1454984538987,
            "version": 1454984538987,
            "shasums": {
                "repo-2.thrift": "repo-2.hash"
>>>>>>> my conflicting local commit
            }
        },
        "repo-2": {
            "time": 1453837638356,
            "version": 1453837638356,
            "shasums": {
                "repo-2.thrift": "repo-2.hash"
            }
        },
        "repo-3": {
<<<<<<< remote commit
            "time": 1453924286124,
            "version": 1453924286124,
=======
            "time": 1454548153744,
            "version": 1454548153744,
>>>>>>> my conflicting local commit
            "shasums": {
                "repo-3.thrift": "repo-3.hash"
            }
        }
    }
}
```

Clearly this is invalid json and no parser would be able to read it. However, since I was not aware `meta.json` had invalid json, I ran `idl update` as usually, and it returned without response. This seemed normal to me (I later remembered I don't actually see no response, I generally see n-1 commas returned, where n is the number of thriftfiles idl is managing).

It was not until I put my change up for code review I saw the meta.json was totally invalid, and the managed thriftfiles had not been updated.

idl should *definitely* be returning an error if meta.json is unparsable. In fact it looks like it used to according to #28, perhaps this is a regression? I was using version 3.1.1

**Comment by malandrew** [comment]
Fixed by https://github.com/uber/idl/pull/37
