### ISSUE TITLE
unhelpful error message when meta.json fails to parse

### ISSUE THREAD

**Issue by blampe** [uber/idl#43]
This isn't a user-friendly error and leads to a lot of confusion:
```
$ idl fetch ...
ERR: SyntaxError: Unexpected string
```

**Comment by blampe** [comment]
Related: why are we seeing so many corrupt meta.json files? Seems to common to be due to bad merges, I'm starting to suspect we're writing incomplete files to disk.

**Comment by malandrew** [comment]
@blampe no idea why. would be impossible to tell without being able to reproduce one of the situations that causes a corrupt meta.json.
