### ISSUE TITLE
fetch dependent/included files

### ISSUE THREAD

**Issue by blampe** [uber/idl#44]
This is a thrift-specific feature request. If I fetch `some.repo/foo.thrift` which includes `bar.thrift` we should automatically issue another fetch for `some.repo/bar.thrift`. We would need to keep track of which files have already been fetched to prevent loops.

**Comment by malandrew** [comment]
get-dependencies was never implemented. It was started, but at the time was not deemed a priority and was shelved.

**Comment by blampe** [comment]
Was that before includes were supported by thriftrw?

**Comment by malandrew** [comment]
Honestly, I haven't a clue. Probably before since the include detection mechanismI used doesn't use our thrift parser.
