### ISSUE TITLE
add support for publishing *.yab files

### ISSUE THREAD

**Issue by blampe** [uber/idl#62]
This would let us bundle yab helper scripts.

cc @kriskowal @akshayjshah @breerly

**Comment by prashantv** [comment]
We'll probably want all `*.yab` files in a subdirectory, and I think `idl` currently ignores subdirectories. We might need to reconsider subdirectory support

**Comment by breerly** [comment]
Why not have them amongst the IDL files?

**Comment by prashantv** [comment]
We can do that, I think it'll be nicer to setup a directory since there'll probably be a lot of `*.yab` files and only one or two `.thrift` files -- might be hard for users to find the `.thrift` file they care about.

**Comment by breerly** [comment]
sgtm, time to break out the node.js :P

**Comment by blampe** [comment]
#41 for reference & agree allowing directories would help people organize these.

**Comment by blampe** [comment]
Good timing, #63 solves the directory problem :P
